import {useEffect,useMemo,useRef,useState,type Dispatch,type SetStateAction} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {ArrowUpRight,BookOpen,Check,Clock3,Download,ExternalLink,Flame,Heart,Pause,Play,Plus,RotateCcw,Target,Trash2,Upload} from 'lucide-react';
import {subjects,totalTopics} from '../data/subjects';
import {distribution,officialUrl,stages,studyWeek} from '../data/edital';
import {taf} from '../data/taf';
import type {TopicStatus,UserData} from '../types';
import {clear,initialData} from '../storage/store';
import {Alert,Empty,PageHeader,Progress,RowLink,Stat} from '../components/UI';
type P={data:UserData;setData:Dispatch<SetStateAction<UserData>>};
const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;
const topicKey=(s:string,t:string)=>`${s}::${t}`;

export function Dashboard({data,setData}:P){const nav=useNavigate();const completed=Object.values(data.topics).filter(x=>x==='completed').length;const q=data.questions.reduce((a,x)=>a+x.total,0),hits=data.questions.reduce((a,x)=>a+x.correct,0);const seconds=data.sessions.reduce((a,x)=>a+x.seconds,0);const weak=[...subjects].sort((a,b)=>subjectProgress(a.id,data)-subjectProgress(b.id,data)).slice(0,3);return <>
 <PageHeader title="Sua preparação começa antes do edital" desc="Visão objetiva do último concurso e do seu ritmo de estudos."><button className="button primary" onClick={()=>nav('/plano')}><Play size={17}/> Iniciar estudo</button></PageHeader>
 <Alert><b>Concurso de referência concluído.</b> Esta plataforma usa o concurso de Soldado CBMMS 2022 para preparação pré-edital. Requisitos, matérias, salário, TAF, banca e demais regras podem mudar.</Alert>
 <section className="hero-card"><div><span className="eyebrow">CONCURSO DE REFERÊNCIA</span><h2>Soldado CBMMS — Concurso 2022</h2><p>Última banca: IDECAN</p></div><span className="badge done">CONCLUÍDO</span></section>
 <div className="stats-grid four"><Stat label="VAGAS" value="250" hint="no último edital"/><Stat label="ESCOLARIDADE" value="Superior" hint="completo, qualquer área"/><Stat label="PROVA" value="80 questões" hint="8 matérias · 4 horas"/><Stat label="MÍNIMO HISTÓRICO" value="40 / 80" hint="sem zerar matéria"/></div>
 <section className="split"><div className="panel"><div className="section-title"><div><span className="eyebrow">SEU RITMO</span><h2>Progresso geral</h2></div><b>{pct(completed,totalTopics)}%</b></div><Progress value={pct(completed,totalTopics)}/><div className="mini-stats"><div><b>{completed}</b><span>de {totalTopics} tópicos</span></div><div><b>{q}</b><span>questões</span></div><div><b>{pct(hits,q)}%</b><span>acertos</span></div><div><b>{(seconds/3600).toFixed(1)}h</b><span>estudadas</span></div><div><b>{data.simulations.length}</b><span>simulados</span></div></div></div>
 <div className="panel"><div className="section-title"><div><span className="eyebrow">FOCO SUGERIDO</span><h2>Próximos estudos</h2></div></div>{weak.map(s=><RowLink key={s.id} title={s.name} meta={`${subjectProgress(s.id,data)}% concluído · ${s.priority}`} onClick={()=>nav('/conteudo/'+s.id)}/>)}</div></section>
 {data.reviews.length>0&&<section className="panel"><div className="section-title"><h2>Revisões pendentes</h2><span>{data.reviews.length} agendadas</span></div>{data.reviews.slice(0,5).map(r=><div className="review-row" key={r.id}><div><b>{r.topic}</b><small>{r.subject} · {new Date(r.date+'T12:00').toLocaleDateString('pt-BR')}</small></div><button className="button ghost" onClick={()=>setData(d=>({...d,reviews:d.reviews.filter(x=>x.id!==r.id)}))}><Check size={16}/> Feita</button></div>)}</section>}
 </>}
function subjectProgress(id:string,data:UserData){const s=subjects.find(x=>x.id===id)!;return pct(s.topics.filter(t=>data.topics[topicKey(id,t)]==='completed').length,s.topics.length)}

export function Edital(){return <><PageHeader title="Resumo do último edital" desc="Dados históricos do concurso de Soldado CBMMS realizado em 2022."/><Alert>Use estas informações como referência de preparação. Confirme todos os requisitos quando um novo edital for publicado.</Alert><div className="info-grid">
 <article className="panel span2"><span className="eyebrow">VAGAS</span><h2>250 vagas</h2><div className="bar-data"><span style={{flex:192}}>192 ampla concorrência</span><span style={{flex:50}}>50 candidatos negros</span><span style={{flex:8}}>8 indígenas</span></div><p>Banca organizadora: <b>IDECAN</b></p></article>
 <article className="panel"><span className="eyebrow">ESCOLARIDADE</span><h2>Nível superior completo</h2><p>Em qualquer área de formação.</p></article><article className="panel"><span className="eyebrow">HABILITAÇÃO</span><h2>CNH B ou superior</h2><p>Era aceita CNH provisória.</p></article>
 <Info title="Idade" value="18 a 30 anos" text="Mínimo de 18 na matrícula do Curso de Formação; máximo de 30 anos, 11 meses e 29 dias no encerramento das inscrições." warn/><Info title="Altura" value="1,65 m / 1,60 m" text="Referência mínima: homens / mulheres."/><Info title="IMC" value="20–28 / 20–26" text="Faixa de referência: homens / mulheres."/><Info title="Lotação" value="Todo o estado" text="Possibilidade de lotação em qualquer município de Mato Grosso do Sul."/>
 <article className="panel span2"><span className="eyebrow">REMUNERAÇÃO HISTÓRICA</span><div className="salary"><div><small>CURSO DE FORMAÇÃO</small><b>R$ 2.252,25</b></div><ArrowUpRight/><div><small>APÓS FORMAÇÃO</small><b>R$ 5.005,00</b></div></div><p>Valores do edital de 2022; não representam necessariamente a remuneração de um próximo concurso.</p></article>
 </div><section className="panel"><div className="section-title"><div><span className="eyebrow">PROVA OBJETIVA</span><h2>80 questões em 4 horas</h2></div><span>5 alternativas por questão</span></div><div className="distribution">{distribution.map(x=><div key={x}><span>{x}</span><b>10</b></div>)}</div><Alert kind="info">O mínimo histórico foi 40/80, sem zerar matéria. Obter a nota mínima não significa necessariamente classificação para as demais fases.</Alert></section></>}
function Info({title,value,text,warn}:{title:string;value:string;text:string;warn?:boolean}){return <article className="panel"><span className="eyebrow">{title}</span><h2>{value}</h2><p>{text}</p>{warn&&<small className="warn-text">Confirme este requisito no próximo edital.</small>}</article>}

export function Stages(){return <><PageHeader title="Etapas do concurso" desc="Sequência adotada no concurso de referência de 2022."/><div className="timeline">{stages.map((s,i)=><details className="stage" key={s}><summary><i>{String(i+1).padStart(2,'0')}</i><div><small>ETAPA {i+1}</small><h3>{s}</h3></div><Plus/></summary><p>{i===0?'Prova objetiva com 80 questões, duração de 4 horas e caráter classificatório conforme as regras históricas.':i===1?'Avaliação de aptidão mental realizada no concurso de referência.':i===2?'Avaliações médicas e exames previstos no edital de referência.':i===3?'Exame eliminatório composto pelos índices físicos detalhados na área de TAF.':i===4?'Avaliação de antecedentes e conduta, sem julgamento automatizado nesta plataforma.':i===5?'Convocação e entrega de documentos conforme regras do edital.':'Etapa de formação após a matrícula.'}</p></details>)}</div></>}

export function Subjects({data}:Omit<P,'setData'>){const nav=useNavigate();return <><PageHeader title="Matérias" desc="Todas tiveram 10 questões na prova objetiva de 2022."/><div className="subject-grid">{subjects.map(s=>{const p=subjectProgress(s.id,data);const qs=data.questions.filter(q=>q.subject===s.id),t=qs.reduce((a,x)=>a+x.total,0),c=qs.reduce((a,x)=>a+x.correct,0);return <article className="subject-card" key={s.id}><div className="subject-top"><span className="subject-icon">{s.short}</span><span className={`priority ${s.priority==='Muito alta'?'hot':''}`}>{s.priority}</span></div><h2>{s.name}</h2><p>10 questões no último concurso · {s.topics.length} tópicos</p><div className="card-progress"><span>Progresso <b>{p}%</b></span><Progress value={p}/></div><div className="subject-foot"><small>Taxa de acerto <b>{t?pct(c,t)+'%':'—'}</b></small><button className="button ghost" onClick={()=>nav('/conteudo/'+s.id)}>Estudar <ArrowUpRight size={16}/></button></div></article>})}</div></>}

export function Content({data,setData}:P){const {id}=useParams();const [active,setActive]=useState(id||subjects[0].id);useEffect(()=>{if(id)setActive(id)},[id]);const s=subjects.find(x=>x.id===active)!;const setStatus=(t:string,status:TopicStatus)=>setData(d=>({...d,topics:{...d.topics,[topicKey(s.id,t)]:status}}));const favorite=(t:string)=>{const k=topicKey(s.id,t);setData(d=>({...d,favorites:d.favorites.includes(k)?d.favorites.filter(x=>x!==k):[...d.favorites,k]}))};const review=(t:string,days:number)=>{const date=new Date();date.setDate(date.getDate()+days);setData(d=>({...d,reviews:[...d.reviews,{id:crypto.randomUUID(),topic:t,subject:s.name,date:date.toISOString().slice(0,10)}]}))};return <><PageHeader title="Conteúdo programático" desc="Marque seu avanço e construa uma fila pessoal de revisão."/><div className="subject-tabs" role="tablist">{subjects.map(x=><button className={active===x.id?'active':''} onClick={()=>setActive(x.id)} key={x.id}>{x.short}<span>{x.name}</span></button>)}</div><section className="panel"><div className="section-title"><div><span className="eyebrow">{s.priority} PRIORIDADE</span><h2>{s.name}</h2><p>{s.topics.length} tópicos do conteúdo de referência</p></div><b>{subjectProgress(s.id,data)}%</b></div><Progress value={subjectProgress(s.id,data)}/>{s.note&&<Alert>{s.note}</Alert>}<div className="topics">{s.topics.map((t,i)=>{const k=topicKey(s.id,t),status=data.topics[k]||'not-started';return <div className="topic" key={t}><span className="topic-num">{String(i+1).padStart(2,'0')}</span><b>{t}</b><button className={`heart ${data.favorites.includes(k)?'active':''}`} onClick={()=>favorite(t)} aria-label="Favoritar"><Heart size={17}/></button><select aria-label={`Status de ${t}`} value={status} onChange={e=>setStatus(t,e.target.value as TopicStatus)}><option value="not-started">Não iniciado</option><option value="studying">Estudando</option><option value="completed">Concluído</option></select><details className="review-menu"><summary>Revisar</summary><div>{[[1,'24h'],[7,'7 dias'],[30,'30 dias']].map(([d,l])=><button key={d} onClick={()=>review(t,+d)}>em {l}</button>)}</div></details></div>})}</div></section>{data.favorites.length>0&&<section className="panel"><div className="section-title"><h2>Revisar depois</h2><span>{data.favorites.length} favoritos</span></div>{data.favorites.map(k=>{const [sid,t]=k.split('::');return <div className="review-row" key={k}><div><b>{t}</b><small>{subjects.find(x=>x.id===sid)?.name}</small></div><Heart className="red" size={18}/></div>})}</section>}</>}

export function StudyPlan({data,setData}:P){return <><PageHeader title="Plano de estudos" desc="Um ciclo semanal inicial, ajustável ao seu tempo disponível."/><section className="week-grid">{studyWeek.map(([day,a,b],i)=><article className={`day ${i===new Date().getDay()-1?'today':''}`} key={day}><span>{day}</span><b>{a}</b><small>{b}</small></article>)}</section><div className="split"><Timer data={data} setData={setData}/><section className="panel"><span className="eyebrow">ROTINA PRONTA</span><h2>{Math.round(data.settings.dailyMinutes/60)} horas por dia</h2><div className="routine"><div><i style={{width:'42%'}}/><b>Teoria</b><span>1h15</span></div><div><i style={{width:'42%'}}/><b>Questões</b><span>1h15</span></div><div><i style={{width:'16%'}}/><b>Revisão</b><span>30min</span></div></div><p>Na rotina de 3 horas. Você pode alterar a meta diária nas configurações.</p></section></div><section className="panel"><div className="section-title"><h2>Histórico de estudos</h2><span>{data.sessions.length} sessões</span></div>{data.sessions.length===0?<Empty title="Nenhuma sessão registrada" desc="Use o cronômetro para iniciar seu histórico real de estudos."/>:data.sessions.slice().reverse().map(x=><div className="review-row" key={x.id}><div><b>{subjects.find(s=>s.id===x.subject)?.name}</b><small>{x.topic||'Estudo geral'} · {new Date(x.date).toLocaleDateString('pt-BR')}</small></div><strong>{Math.round(x.seconds/60)} min</strong></div>)}</section></>}
function Timer({data,setData}:P){const [subject,setSubject]=useState(subjects[0].id),[topic,setTopic]=useState(''),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false);const ref=useRef<number|undefined>(undefined);useEffect(()=>{if(running)ref.current=window.setInterval(()=>setSeconds(x=>x+1),1000);return()=>clearInterval(ref.current)},[running]);const finish=()=>{if(seconds>0)setData({...data,sessions:[...data.sessions,{id:crypto.randomUUID(),subject,topic,seconds,date:new Date().toISOString()}]});setRunning(false);setSeconds(0)};return <section className="panel timer"><span className="eyebrow">CRONÔMETRO DE ESTUDO</span><div className="time">{new Date(seconds*1000).toISOString().slice(11,19)}</div><div className="form-row"><label>Matéria<select value={subject} onChange={e=>{setSubject(e.target.value);setTopic('')}}>{subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Tópico<select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Estudo geral</option>{subjects.find(s=>s.id===subject)?.topics.map(t=><option key={t}>{t}</option>)}</select></label></div><div className="timer-actions"><button className="button primary" onClick={()=>setRunning(!running)}>{running?<><Pause/>Pausar</>:<><Play/>Iniciar</>}</button><button className="button ghost" onClick={finish}><Check/>Finalizar</button><button className="icon" onClick={()=>{setRunning(false);setSeconds(0)}} aria-label="Zerar"><RotateCcw/></button></div></section>}

export function Performance({data,setData}:P){const [tab,setTab]=useState<'q'|'s'>('q');const chart=data.simulations.map((s,i)=>({name:`S${i+1}`,percent:pct(s.correct,s.total)}));return <><PageHeader title="Questões e desempenho" desc="Registre apenas seus resultados reais e acompanhe a evolução."/><div className="segmented"><button className={tab==='q'?'active':''} onClick={()=>setTab('q')}>Questões</button><button className={tab==='s'?'active':''} onClick={()=>setTab('s')}>Simulados</button></div>{tab==='q'?<QuestionForm data={data} setData={setData}/>:<SimulationForm data={data} setData={setData}/>}<div className="split"><section className="panel"><h2>{tab==='q'?'Desempenho por matéria':'Evolução nos simulados'}</h2>{tab==='q'?(data.questions.length===0?<Empty title="Sem questões registradas" desc="O painel será calculado a partir dos seus lançamentos."/>:<div className="score-list">{subjects.map(s=>{const a=data.questions.filter(x=>x.subject===s.id),t=a.reduce((n,x)=>n+x.total,0),c=a.reduce((n,x)=>n+x.correct,0);return t?<div key={s.id}><span>{s.name}<b>{pct(c,t)}%</b></span><Progress value={pct(c,t)}/></div>:null})}</div>):(chart.length===0?<Empty title="Sem simulados" desc="Registre seu primeiro simulado para gerar o gráfico."/>:<div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="red" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d94242" stopOpacity={.5}/><stop offset="1" stopColor="#d94242" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip/><Area dataKey="percent" stroke="#e44b4b" fill="url(#red)"/></AreaChart></ResponsiveContainer></div>)}</section><section className="panel"><span className="eyebrow">META ESTRATÉGICA</span><h2>{data.settings.simulationGoal} a 70+ acertos</h2><p>Meta configurável de preparação. Não é uma nota oficial de corte nem garantia de classificação.</p><div className="target-ring"><Target/><span>Foco em<br/><b>consistência</b></span></div></section></div></>}
function QuestionForm({data,setData}:P){const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),total=+f.get('total')!,correct=+f.get('correct')!;if(correct>total)return;setData({...data,questions:[...data.questions,{id:crypto.randomUUID(),subject:String(f.get('subject')),total,correct,date:String(f.get('date'))}]});e.currentTarget.reset()};return <form className="entry-form panel" onSubmit={submit}><label>Matéria<select name="subject">{subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Questões<input required min="1" type="number" name="total"/></label><label>Acertos<input required min="0" type="number" name="correct"/></label><label>Data<input required type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><button className="button primary"><Plus/> Registrar</button></form>}
function SimulationForm({data,setData}:P){const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),total=+f.get('total')!,correct=+f.get('correct')!;if(correct>total)return;setData({...data,simulations:[...data.simulations,{id:crypto.randomUUID(),name:String(f.get('name')),date:String(f.get('date')),total,correct,minutes:+f.get('minutes')!}]});e.currentTarget.reset()};return <form className="entry-form panel" onSubmit={submit}><label>Nome<input required name="name" placeholder="Simulado 01"/></label><label>Data<input required type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Total<input required min="1" type="number" name="total" defaultValue="80"/></label><label>Acertos<input required min="0" type="number" name="correct"/></label><label>Tempo (min)<input required min="1" type="number" name="minutes"/></label><button className="button primary"><Plus/> Registrar</button></form>}

export function Taf({data,setData}:P){const [gender,setGender]=useState<keyof typeof taf>('Masculino');return <><PageHeader title="TAF e saúde" desc="Índices de referência e acompanhamento pessoal de preparação física."/><Alert><b>Índices baseados no concurso de 2022.</b> Consulte obrigatoriamente o próximo edital quando publicado.</Alert><div className="segmented"><button className={gender==='Masculino'?'active':''} onClick={()=>setGender('Masculino')}>Masculino</button><button className={gender==='Feminino'?'active':''} onClick={()=>setGender('Feminino')}>Feminino</button></div><div className="taf-grid">{taf[gender].map(([name,goal])=><article className="panel taf-card" key={name}><span>{name}</span><h2>{goal}</h2><label>Seu resultado<input value={data.taf[gender+name]||''} onChange={e=>setData(d=>({...d,taf:{...d.taf,[gender+name]:e.target.value}}))} placeholder="Registrar resultado"/></label></article>)}</div><section className="panel"><span className="eyebrow">EXAME DE SAÚDE — REFERÊNCIA</span><h2>Avaliações previstas em 2022</h2><div className="tag-list">{['Altura','IMC','Força de preensão manual','Avaliação odontológica','Visão','Audição','Exames laboratoriais','Toxicológico','Outros exames do edital'].map(x=><span key={x}>{x}</span>)}</div><Alert kind="info">Somente profissionais e avaliações oficiais podem determinar aptidão médica. Esta seção não realiza autodiagnóstico.</Alert></section><section className="panel"><span className="eyebrow">INVESTIGAÇÃO SOCIAL</span><h2>Antecedentes e conduta</h2><p>O concurso de referência incluía essa avaliação. A plataforma não faz julgamentos ou classificações automáticas de apto/inapto.</p></section></>}

export function Documents(){return <><PageHeader title="Documentos e fontes" desc="Acesso ao concurso de referência sem URLs não verificadas."/><section className="panel official"><div className="official-icon"><LandmarkIcon/></div><div><span className="eyebrow">FONTE OFICIAL EXTERNA</span><h2>Portal de Concursos do Governo de Mato Grosso do Sul</h2><p>Página principal do concurso de Soldado CBMMS 2022.</p></div><a className="button primary" href={officialUrl} target="_blank" rel="noreferrer">Acessar portal <ExternalLink/></a></section><section className="panel"><div className="section-title"><div><span className="eyebrow">PROVAS ANTERIORES</span><h2>CBMMS Soldado 2022</h2></div></div><div className="docs-grid">{['Prova Tipo A','Prova Tipo B','Edital','Gabarito','Outros documentos'].map(x=><div className="doc-placeholder" key={x}><FileMark/><div><b>{x}</b><small>Consulte no portal oficial</small></div></div>)}</div><p className="muted">Links diretos não foram adicionados porque não foram fornecidos no projeto. Use o portal oficial acima.</p></section></>}
function LandmarkIcon(){return <Flame/>} function FileMark(){return <BookOpen/>}

export function SettingsPage({data,setData}:P){const file=useRef<HTMLInputElement>(null);const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='linha-de-frente-backup.json';a.click();URL.revokeObjectURL(a.href)};const importData=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setData({...initialData,...JSON.parse(String(r.result))})}catch{alert('Arquivo JSON inválido.')}};r.readAsText(f)};const wipe=()=>{if(confirm('Apagar todo o progresso local? Esta ação não pode ser desfeita.')){clear();setData(initialData)}};return <><PageHeader title="Configurações" desc="Metas pessoais e controle dos dados armazenados neste dispositivo."/><div className="settings-grid"><section className="panel"><span className="eyebrow">METAS</span><h2>Rotina de preparação</h2><label>Meta diária<select value={data.settings.dailyMinutes} onChange={e=>setData(d=>({...d,settings:{...d.settings,dailyMinutes:+e.target.value}}))}>{[60,120,180,240].map(x=><option value={x} key={x}>{x/60} hora{x>60?'s':''}</option>)}</select></label><label>Questões por dia<input type="number" min="1" value={data.settings.questionGoal} onChange={e=>setData(d=>({...d,settings:{...d.settings,questionGoal:+e.target.value}}))}/></label><label>Meta do simulado (acertos)<input type="number" min="1" max="80" value={data.settings.simulationGoal} onChange={e=>setData(d=>({...d,settings:{...d.settings,simulationGoal:+e.target.value}}))}/></label></section><section className="panel"><span className="eyebrow">SEUS DADOS</span><h2>Backup local</h2><p>Exporte um arquivo JSON para guardar ou transferir seu progresso.</p><div className="stack-actions"><button className="button ghost" onClick={exportData}><Download/> Exportar dados</button><button className="button ghost" onClick={()=>file.current?.click()}><Upload/> Importar dados</button><input hidden ref={file} type="file" accept="application/json" onChange={importData}/><button className="button danger" onClick={wipe}><Trash2/> Limpar todos os dados</button></div></section></div><Alert kind="info">Tudo é salvo somente no armazenamento local deste navegador. Não há conta ou sincronização em nuvem nesta versão.</Alert></>}
