import {NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {useState} from 'react';
import {BookOpen,ChartNoAxesCombined,ClipboardCheck,Dumbbell,FileText,Gauge,GraduationCap,Landmark,LayoutDashboard,Menu,Search,Settings,Shield,TimerReset,X} from 'lucide-react';
import {subjects} from '../data/subjects';

const nav=[['/','Visão geral',LayoutDashboard],['/edital','Último edital',FileText],['/etapas','Etapas',ClipboardCheck],['/materias','Matérias',BookOpen],['/conteudo','Conteúdo',GraduationCap],['/plano','Plano de estudos',TimerReset],['/desempenho','Desempenho',ChartNoAxesCombined],['/taf','TAF e saúde',Dumbbell],['/documentos','Documentos',Landmark],['/configuracoes','Configurações',Settings]] as const;
export default function Layout(){const [open,setOpen]=useState(false);const [search,setSearch]=useState(false);const loc=useLocation();const navigate=useNavigate();return <div className="shell">
 <aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-shield"><Shield size={22}/></div><div><b>LINHA DE FRENTE</b><small>PREPARAÇÃO CBMMS</small></div><button className="icon close" onClick={()=>setOpen(false)} aria-label="Fechar menu"><X/></button></div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={19}/><span>{label}</span></NavLink>)}</nav><div className="side-note"><b>BASE HISTÓRICA</b><span>Edital de Soldado 2022</span><em>CONCLUÍDO</em></div></aside>
 <main><header className="topbar"><button className="icon menu" onClick={()=>setOpen(true)} aria-label="Abrir menu"><Menu/></button><div className="crumb">CBMMS <span>/</span> {nav.find(([p])=>p===loc.pathname)?.[1]||'Conteúdo programático'}</div><button className="search-btn" onClick={()=>setSearch(true)}><Search size={18}/><span>Buscar matéria ou tópico</span><kbd>⌘ K</kbd></button><div className="status-dot"><i/> Dados salvos</div></header><div className="content"><Outlet/></div>
 <nav className="mobile-nav">{nav.slice(0,4).map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'}><Icon/><span>{label}</span></NavLink>)}<button onClick={()=>setOpen(true)}><Menu/><span>Mais</span></button></nav></main>
 {search&&<div className="modal-bg" onMouseDown={()=>setSearch(false)}><div className="search-modal" onMouseDown={e=>e.stopPropagation()}><Search/><input autoFocus placeholder="Ex.: crase, corrida, CNH..." onChange={e=>{const v=e.target.value.toLowerCase();document.querySelectorAll('.search-result').forEach(el=>el.classList.toggle('hide',!el.textContent?.toLowerCase().includes(v)))}}/><button className="icon" onClick={()=>setSearch(false)}><X/></button><div className="search-results">{subjects.flatMap(s=>s.topics.map(t=><button className="search-result" key={s.id+t} onClick={()=>{navigate('/conteudo/'+s.id);setSearch(false)}}><span>{t}</span><small>{s.name}</small></button>))}</div></div></div>}
 </div>}
